#include "FontFamily.h"

const std::wstring FontFamily::fontFamilyList[] = {
		L"Arial",
		L"Bahnschrift",
		L"Calibri",
		L"Cambria",
		L"Cambria Math",
		L"Candara",
		L"Comic Sans MS",
		L"Consolas",
		L"Constantia",
		L"Corbel",
		L"Courier New",
		L"Ebrima",
		L"Franklin Gothic",
		L"Gabriola",
		L"Gadugi",
		L"Georgia",
		L"Impact",
		L"Ink Free",
		L"Javanese Text",
		L"Leelawadee UI",
		L"Lucida Console",
		L"Lucida Sans Unicode",
		L"Malgun Gothic",
		L"Microsoft Himalaya",
		L"Microsoft JhengHei",
		L"Microsoft JhengHei UI",
		L"Microsoft New Tai Lue",
		L"Microsoft PhagsPa",
		L"Microsoft Sans Serif",
		L"Microsoft Tai Le",
		L"Microsoft YaHei",
		L"Microsoft YaHei UI",
		L"Microsoft Yi Baiti",
		L"MingLiU-ExtB",
		L"PMingLiU-ExtB",
		L"MingLiU_HKSCS-ExtB",
		L"Mongolian Baiti",
		L"MS Gothic",
		L"MS UI Gothic",
		L"MS PGothic",
		L"MV Boli",
		L"Myanmar Text",
		L"Nirmala UI",
		L"Palatino Linotype",
		L"Segoe MDL2 Assets",
		L"Segoe Print",
		L"Segoe Script",
		L"Segoe UI",
		L"Segoe UI Emoji",
		L"Segoe UI Historic",
		L"Segoe UI Symbol",
		L"SimSun",
		L"NSimSun",
		L"SimSun-ExtB",
		L"Sitka Small",
		L"Sitka Text",
		L"Sitka Subheading",
		L"Sitka Heading",
		L"Sitka Display",
		L"Sitka Banner",
		L"Sylfaen",
		L"Symbol",
		L"Tahoma",
		L"Times New Roman",
		L"Trebuchet MS",
		L"Verdana",
		L"Webdings",
		L"Wingdings",
		L"Yu Gothic",
		L"Yu Gothic UI",
		L"Hololens MDL2 Assets",
		L"Agency FB",
		L"Algerian",
		L"Book Antiqua",
		L"Arial Rounded MT",
		L"Baskerville Old Face",
		L"Bauhaus 93",
		L"Bell MT",
		L"Bernard MT",
		L"Bodoni MT",
		L"Bodoni MT Poster",
		L"Bookman Old Style",
		L"Bradley Hand ITC",
		L"Britannic",
		L"Berlin Sans FB",
		L"Broadway",
		L"Brush Script MT",
		L"Bookshelf Symbol 7",
		L"Californian FB",
		L"Calisto MT",
		L"Castellar",
		L"Century Schoolbook",
		L"Centaur",
		L"Century",
		L"Chiller",
		L"Colonna MT",
		L"Cooper",
		L"Copperplate Gothic",
		L"Curlz MT",
		L"Dubai",
		L"Elephant",
		L"Engravers MT",
		L"Eras ITC",
		L"Felix Titling",
		L"Forte",
		L"Franklin Gothic Book",
		L"Freestyle Script",
		L"Freestyle Script MT",
		L"Footlight MT",
		L"Garamond",
		L"Gigi",
		L"Gill Sans MT",
		L"Gill Sans",
		L"Gloucester MT",
		L"Century Gothic",
		L"Goudy Old Style",
		L"Goudy Stout",
		L"Harlow Solid",
		L"Harrington",
		L"Haettenschweiler",
		L"High Tower Text",
		L"Imprint MT Shadow",
		L"Informal Roman",
		L"Blackadder ITC",
		L"Edwardian Script ITC",
		L"Kristen ITC",
		L"Jokerman",
		L"Juice ITC",
		L"Kunstler Script",
		L"Wide Latin",
		L"Lucida Bright",
		L"Lucida Calligraphy",
		L"Lucida Fax",
		L"Lucida Handwriting",
		L"Lucida Sans",
		L"Lucida Sans Typewriter",
		L"Magneto",
		L"Maiandra GD",
		L"Matura MT Script Capitals",
		L"Mistral",
		L"Modern No. 20",
		L"Monotype Corsiva",
		L"MT Extra",
		L"Niagara Engraved",
		L"Nigara Solid",
		L"OCR A",
		L"Old English Text MT",
		L"Onyx",
		L"MS Outlook",
		L"Palace Script MT",
		L"Papyrus",
		L"Parchment",
		L"Perpetua",
		L"Perpetual Titling MT",
		L"Playbill",
		L"Poor Richard",
		L"Pristina",
		L"Rage",
		L"Ravie",
		L"MS Reference Sans Serif",
		L"MS Reference Specialty",
		L"Rockwell",
		L"Script MT",
		L"Showcard Gothic",
		L"Snap ITC",
		L"Stencil",
		L"Tw Cen MT",
		L"Tempus Sans ITC",
		L"Viner Hand ITC",
		L"Vivaldi",
		L"Vladimir Script",
		L"Wingdings 2",
		L"Wingdings 3",
		L"Marlett"
};