#pragma once
#include "pch.h"

#include <string>

enum FONT_FAMILY
{
	ARIAL,
	BAHNSCHRIFT,
	CALIBRI,
	CAMBRIA,
	CAMBRIA_MATH,
	CANDARA,
	COMIC_SANS_MS, // Comic Sans MS
	CONSOLAS,
	CONSTANTIA,
	CORBEL,
	COURIER_NEW,
	EBRIMA,
	FRANKLIN_GOTHIC,
	GABRIOLA,
	GADUGI,
	GEORGIA,
	IMPACT,
	INK_FREE,
	JAVANESE_TEXT,
	LEELAWADEE_UI, // Leelawadee UI
	LUCIDA_CONSOLE,
	LUCIDA_SANS_UNICODE,
	MALGUN_GOTHIC,
	MICROSOFT_HIMALAYA,
	MICROSOFT_JHENGHEI, // Microsoft JhengHei
	MICROSOFT_JHENGHEI_UI, // Microsoft JhengHei UI
	MICROSOFT_NEW_TAI_LUE,
	MICROSOFT_PHAGSPA, // Microsoft PhagsPa
	MICROSOFT_SANS_SERIF,
	MICROSOFT_TAI_LE,
	MICROSOFT_YAHEI, // Microsoft YaHei
	MICROSOFT_YAHEI_UI, // Microsoft YaHei UI
	MICROSOFT_YI_BAITI,
	MINGLIU_EXTB, // MingLiU-ExtB
	PMINGLIU_EXTB, // PMingLiU-ExtB
	MINGLIU_HKSCS_EXTB, // MingLiU_HKSCS-ExtB
	MONGOLIAN_BAITI,
	MS_GOTHIC, // MS Gothic
	MS_UI_GOTHIC, // MS UI Gothic
	MS_PGOTHIC, // MS PGothic
	MV_BOLI, // MV Boli
	MYANMAR_TEXT,
	NIRMALA_UI, // Nirmala UI
	PALATINO_LINOTYPE,
	SEGOE_MDL2_ASSETS, // Segoe MDL2 Assets
	SEGOE_PRINT,
	SEGOE_SCRIPT,
	SEGOE_UI, // Segoe UI
	SEGOE_UI_EMOJI, // Segoe UI Emoji
	SEGOE_UI_HISTORIC, // Segoe UI Historic
	SEGOE_UI_SYMBOL, // Segoe UI Symbol
	SIMSUN, // SimSun
	NSIMSUN, // NSimSun
	SIMSUN_EXTB, // SimSun-ExtB
	SITKA_SMALL,
	SITKA_TEXT,
	SITKA_SUBHEADING,
	SITKA_HEADING,
	SITKA_DISPLAY,
	SITKA_BANNER,
	SYLFAEN,
	SYMBOL,
	TAHOMA,
	TIMES_NEW_ROMAN,
	TREBUCHET_MS, // Trebuchet MS
	VERDANA,
	WEBDINGS,
	WINGDINGS,
	YU_GOTHIC,
	YU_GOTHIC_UI, // Yu Gothic UI
	HOLOLENS_MDL2_ASSETS, // Hololens MDL2 Assets
	AGENCY_FB, // Agency FB
	ALGERIAN,
	BOOK_ANTIQUA,
	ARIAL_ROUNDED_MT, // Arial Rounded MT
	BASKERVILLE_OLD_FACE,
	BAUHAUS_93,
	BELL_MT, // Bell MT
	BERNARD_MT, // Bernard MT
	BODONI_MT, // Bodoni MT
	BODONI_MT_POSTER, // Bodoni MT Poster
	BOOKMAN_OLD_STYLE,
	BRADLEY_HAND_ITC, // Bradley Hand ITC
	BRITANNIC,
	BERLIN_SANS_FB, // Berlin Sans FB
	BROADWAY,
	BRUSH_SCRIPT_MT, // Brush Script MT
	BOOKSHELF_SYMBOL_7,
	CALIFORNIAN_FB, // Californian FB
	CALISTO_MT, // Calisto MT
	CASTELLAR,
	CENTURY_SCHOOLBOOK,
	CENTAUR,
	CENTURY,
	CHILLER,
	COLONNA_MT, // Colonna MT
	COOPER,
	COPPERPLATE_GOTHIC,
	CURLZ_MT, // Curlz MT
	DUBAI,
	ELEPHANT,
	ENGRAVERS_MT, // Engravers MT
	ERAS_ITC, // Eras ITC
	FELIX_TITLING,
	FORTE,
	FRANKLIN_GOTHIC_BOOK,
	FREESTYLE_SCRIPT,
	FRENCH_SCRIPT_MT, // Freestyle Script MT
	FOOTLIGHT_MT, // Footlight MT
	GARAMOND,
	GIGI,
	GILL_SANS_MT, // Gill Sans MT
	GILL_SANS,
	GLOUCESTER_MT, // Gloucester MT
	CENTURY_GOTHIC,
	GOUDY_OLD_STYLE,
	GOUDY_STOUT,
	HARLOW_SOLID,
	HARRINGTON,
	HAETTENSCHWEILER,
	HIGH_TOWER_TEXT,
	IMPRINT_MT_SHADOW, // Imprint MT Shadow
	INFORMAL_ROMAN,
	BLACKADDER_ITC, // Blackadder ITC
	EDWARDIAN_SCRIPT_ITC, // Edwardian Script ITC
	KRISTEN_ITC, // Kristen ITC
	JOKERMAN,
	JUICE_ITC, // Juice ITC
	KUNSTLER_SCRIPT,
	WIDE_LATIN,
	LUCIDA_BRIGHT,
	LUCIDA_CALLIGRAPHY,
	LUCIDA_FAX,
	LUCIDA_HANDWRITING,
	LUCIDA_SANS,
	LUCIDA_SANS_TYPEWRITER,
	MAGNETO,
	MAIANDRA_GD, // Maiandra GD
	MATURA_MT_SCRIPT_CAPITALS, // Matura MT Script Capitals
	MISTRAL,
	MODERN_NO_20, // Modern No. 20
	MONOTYPE_CORSIVA,
	MT_EXTRA, // MT Extra
	NIAGARA_ENGRAVED,
	NIAGARA_SOLID,
	OCR_A, // OCR A
	OLD_ENGLISH_TEXT_MT, // Old English Text MT
	ONYX,
	MS_OUTLOOK, // MS Outlook
	PALACE_SCRIPT_MT, // Palace Script MT
	PAPYRUS,
	PARCHMENT,
	PERPETUA,
	PERPETUA_TITLING_MT, // Perpetual Titling MT
	PLAYBILL,
	POOR_RICHARD,
	PRISTINA,
	RAGE,
	RAVIE,
	MS_REFERENCE_SANS_SERIF, // MS Reference Sans Serif
	MS_REFERENCE_SPECIALTY, // MS Reference Specialty
	ROCKWELL,
	SCRIPT_MT, // Script MT
	SHOWCARD_GOTHIC,
	SNAP_ITC, // Snap ITC
	STENCIL,
	TW_CEN_MT, // Tw Cen MT
	TEMPUS_SANS_ITC, // Tempus Sans ITC
	VINER_HAND_ITC, // Viner Hand ITC
	VIVALDI,
	VLADIMIR_SCRIPT,
	WINGDINGS_2,
	WINGDINGS_3,
	MARLETT
};

//std::wstring FontFamilyToWString(FontFamily fontFamily)
//{
//	return fontFamilyList[fontFamily];
//}

class FontFamily
{
public:
	static std::wstring ToWString(FONT_FAMILY family) { return fontFamilyList[family]; }

private:
	static const std::wstring fontFamilyList[];
};

